### ISSUE TITLE
Add a Robot Inspector window

### ISSUE THREAD

**Issue by ldicker83** [OutpostUniverse/OPHD#136]
Related to #55 and #72 , this window should be brought up when the user right-clicks a tile with a Robot in it.

![image](https://user-images.githubusercontent.com/13858902/72225774-46888380-3557-11ea-82e1-8c01c0f34185.png)

**Comment by belgianguy** [comment]
As I just got Eclipse to be able to run [Debug builds](https://forum.outpost2.net/index.php/topic,6321.msg88997.html#msg88997) of OPHD, I thought why not actually try and add some code.

So I stumbled upon this issue. Bear with me, I have no experience with this codebase (and I'm a Java programmer during the day). But I've dabbed in C++ in uni and in my free time.
I also have no idea if this issue was already assigned to someone, I merely wanted a test run for the compiler and see if I could get something to work.

Regarding the issue, I realized that I had already seen some structures already display such an inspector window mechanic, so took screenshots of those. 
That way I could locate the hard coded strings, and find out what was calling these strings.

Through the Constant **WINDOW_STRUCTURE_INSPECTOR** I finally ended up in StructureInspector. While from a naive point of view the logic here seems to do what is needed for the RobotInspector, but with some diferences:
- Robot isn't created with a RobotClass (as a counterpart to StructureClass), but there exists such a thing as RobotType.
- Robot doesn't have a RobotState enum, (as a counterpart to StructureState), as I see it, a Robot could be OPERATIONAL, IDLE, DISABLED (ran out of fuel?), DESTROYED (meteor impact?), but there maybe is a good reason that they don't have this?
- The UI mockup shows a larger sprite, does that exist already?
- The popup title could be the RobotType
- Its age would be the fuelCellAge
- The buttons would be some extra research into NAS2D, but I assume the close window logic could in abstract ways cover that.

At this point I realised that I was now forcing the Robot object to start adapting to the Structure object, even though that could potentially lead to some good outcomes, it could also pull in dependencies that are not wanted. And if the StructureInspector was nearly identical to the RobotInspector, would that then also not demand an "Inspector" interface at one point?

At this point I stopped and reverted what I already had and came here :).

So any advice on what would be a good plan of attack here? Certain code structures I could look at to see what is needed, and what is not needed? Any gotcha's? How does it "tick" ? :)

**Comment by DanRStevens** [comment]
Oh hey, welcome.

I'm still trying to figure out some of the GUI code myself. There's been some refactoring going on to make the code easier to deal with. Some of the user interface code got a bit of an update not long ago. Sounds like you've hit an area where a bit of refactoring may still be needed.

I'm wondering if some kind of base class interface might reduce the amount of code that will be needed here. There are a few places where I suspect copy/paste code can be avoiding by finding better abstractions. It can be a little difficult to figure out what those abstractions should be though.

From what you're saying, maybe there are commonalities between `Robot` and `Structure` that could be exploited. If so, then the already existing popup window could potentially be generalized to work for either. This is a bit of guesswork though, since I'm not familiar with that code.

If you want to look further into the matter, or offer suggestions, I would be most curious to see what you could come up with. Feel free to post specific snippets of code if you have particular questions, or to highlight anything you're struggling with.

**Comment by belgianguy** [comment]
Okay, so I redid my changes, as I have not yet enough understanding of the whole code landscape, trying to abstract away too early could possibly break more than it fixes.

I saw the following in Tile.cpp:

`/**
 * 
 */
Robot* Tile::robot()
{
	// Assumption: Things in a tile can only be a Robot or a Structure. If the thing is not a
	// structure, it can only be a robot.
	if (!empty() && structure() == nullptr) { return static_cast<Robot*>(thing()); }

	return nullptr;
}`

I've added a RobotState and RobotClass member to Robot. The state is updated through its lifecycle from IDLE -> OPERATIONAL -> IDLE at the moment.

![robot_inspector](https://user-images.githubusercontent.com/3091512/80913411-b9a34900-8d44-11ea-802b-6ab901a97fcc.png)

**Comment by DanRStevens** [comment]
Hi, thanks for taking an interest.

So I took a quick look over your changes. They look quite reasonable, and the code style nicely matches existing code.

----

The assumption that a `Thing` which is not a `Structure` must be a `Robot` sounds reasonable. I think what I might suggest here, is to add a `thingIsRobot` method to `Tile`, to complement the `thingIsStructure` method. That way the assumption is documented by active code, and doesn't need a comment.

Possible implementation:
```cpp
bool thingIsRobot() const { return !mThingIsStructure; }
```

The UI code would then look something like:
```cpp
else if (_t->thingIsRobot())
{
  Robot* robot = _t->robot();
  // ...
}
```

Future refactoring note: We could use `auto*` in place of `Structure*` and `Robot*`, so we avoid unnecessarily repeating type information. I just noticed that about the original code there.

----

The `RobotClass` enum feels a bit redundant. It's basically restating class type information. In cases like this, I might normally suggest adding a virtual method to the base class to return the needed information. The method could be overridden in the derived class to return type specific values.

Actually, if all the field is used for, is to get the type name of the robot, we could potentially use the `name()` accessor, which already exists. Not sure if the formatting is quite the same, but if it's suitable, that may be ideal.

----

Maybe @ldicker83 can comment on the `RobotState` enum. I'm less familiar with this area, so I'm uncertain what is suitable there. It seems reasonable, though I'm uncertain if robots can be `DISABLED`. Definition given was:
```cpp
enum RobotState
{
	OPERATIONAL,
	IDLE,
	DISABLED,
	DESTROYED
};
```

----

In preparation for a Pull Request, and this is getting a bit into personal preference, I might suggest splitting changes to support code into their own commit, before the new feature additions. In this case, changes to the `Robot` classes could become their own commit, before the new UI class additions. Whenever possible, I look for ways to split changes into smaller more highly targeted commits, (with the one restriction that each commit should compile on its own).

**Comment by belgianguy** [comment]
Hi @DanRStevens,

Thanks for the feedback, I agree with your comments. 
The 'tile contains a robot if no structure is there' comment was already there, but I indeed felt a bit eery to "default" to it being a Robot. I'll add that code and remove the comment. I guess I could take up the auto* change too.

I added the RobotClass type based on what I saw was used in the StructureInspector, and it might be redundant. I added it more out of (my limited view of) consistency. As Structures have a name too, and that wasn't used in the StructureInspector.

The RobotState is something that isn't totally clear to me either, I've only used IDLE and OPERATIONAL for now I had in mind the following idea:
- IDLE: not doing anything, but available to do tasks
- OPERATIONAL: currently executing a task, running a turn will decrement the task turns.
- DISABLED: unable to further execute its task (eg:  The Comm Tower providing a RoboDigger with data is destroyed by a disaster/explosion of Hot Lab/Tokamak, putting the RoboDigger out of range of base communication), player intervention needed (build a new Comm. Tower with that RoboDigger in its range). Task is frozen and robot unavailble until DISABLED reason is resolved.
- DESTROYED: eg when a Dozer gets impacted by a meteor, or was next to a Hot Lab/Tokamak when it exploded. Task is unable to be finished and will be rolled back to initial state. The Robot object is removed the next turn (caution with UI panels still open referencing them)

With regards to the commits, do you have any reference commits/issues that follow that pattern?
As I tried really hard to make nice delineated commits, but it appears the Debug/Eclipse files are now also in the branch. So I'll need to brush up some on more meticulous commits, any resources regarding that would be welcome.

**Comment by DanRStevens** [comment]
Ahh. My ignorance of that section of the code shines through then. I'm not completely aware of all the idioms used in that section of the code. I thought the comments were illustrative, and wasn't aware of the `StructureClass` enum.

----

The proposed values for `RobotState` make sense to me.

----

I don't have any particular reference handy for how to break up commits. I suppose checking git log might provide some examples.
Command line example:
```
git log -p
```

In terms of reworking code into a nice presentation, I've found interactive git rebase to be extremely valuable. I can make commits as I figure stuff out, then when I realize I've made a mistake, or have gone about the problem the wrong way, I can use git rebase to rewrite history, and do things in a better way. Makes the final results a little easier to understand when it comes time for a code review.
Command line example:
```
git rebase -i master
```

Judicious use of the git index to stage files, and git stash for the remaining changes means I can test and chunk change sets, keeping commits smaller and more targetted.
Command line example:
```
git add <SomeSetOfFiles>  # Optionally "-p" for parts of files
git stash --keep-index  # Stash only the changes that were not added to the index
make  # Test compile with a clean set of changes
git commit
git stash pop
```

**Comment by ldicker83** [comment]
Hey all,

So, going to try to address everything here but there's a lot so bear with me.

Robots and Structures are two different beasts. It's why there's the concept of a 'class' for structures but not robots -- they indicate things like labs, power generators, storage, etc. It's a way to categorize structures so that they can be grouped and updated in a set order. This is done in the `StructureManager` class:

```cpp
void StructureManager::update(ResourcePool& resourcePool, PopulationPool& popPool)
{
	// Called separately so that 1) high priority structures can be updated first and
	// 2) so that resource handling code (like energy) can be handled between update
	// calls to lower priority structures.
	updateStructures(resourcePool, popPool, mStructureLists[Structure::StructureClass::CLASS_LANDER]); // No resource needs
	updateStructures(resourcePool, popPool, mStructureLists[Structure::StructureClass::CLASS_COMMAND]); // Self sufficient
	updateStructures(resourcePool, popPool, mStructureLists[Structure::StructureClass::CLASS_ENERGY_PRODUCTION]); // Nothing can work without energy

	updateEnergyProduction(resourcePool, popPool);

	// Basic resource production
	updateStructures(resourcePool, popPool, mStructureLists[Structure::StructureClass::CLASS_MINE]); // Can't operate without resources.

	/* ...snip... */

	updateStructures(resourcePool, popPool, mStructureLists[Structure::StructureClass::CLASS_UNDEFINED]);

	updateFactoryProduction();
}
```

Robots aren't updated the same way so there was no need to group them into classes like that. Plus, there are far fewer robot types than structure types. The initial plan is to have Diggers, Dozers, Miners, Trucks and Explorers. There may be a couple more types of robots but they don't need to be grouped by type like structures do.

Robots are updated each turn in the [`void MapViewState::updateRobots()`](https://github.com/OutpostUniverse/OPHD/blob/master/OPHD/States/MapViewState.cpp#L1267) function. It's a fairly large function which is why I'm linking to it instead of posting it. The basic structure of the function is this:

1. Iterate through all robots in the robot list and call `Robot::update()` on each one.
2. Check if the robot is dead. If it is, handle it (there's a bunch of things involved in doing that properly, namely removing it from the robot list, removing it from whatever Robot Command Center it's part of and ensuring that the iterator isn't invalidated in the process.)
3. If the robot is Idle, remove it from the robot list and the tile that it's in.
4. If neither of these are true, increment the iterator
5. Finally, update the robot command control (see [here](https://github.com/OutpostUniverse/OPHD/blob/master/OPHD/States/MapViewStateHelper.cpp#L278))

As a note, the 'robot list' is a list of robots that are active and somewhere on the tilemap. Currently, when a robot 'dies' it's removed entirely from the game. The basic idea here is that it's more costly and dangerous to retrieve a broken down robot and repair it than it is to simply build and deploy a new one. There's also some special case code that determines what a robot was doing to provide messaging to the end user and to revert the tile state to where it was before the robot began its work.

---

With all that stated, basically, Robots and Structures are entirely different creatures and are handled differently by the game.

Regarding this issue, the titles for the windows may be the same but the function is very different. The Structure Inspector is intended to give an overview of the Structure that you're looking at including population requirements, status, reason for disabled, etc. The Robot Inspector window will have some overlap but it's intention is to give the player the ability to get an idea of how many turns remain to complete a task and to give the option to recall or self destruct a robot. Knowing the age of a robot also gives the user the option to recall it for recycling or to set it to self destruct (for instance, to clear impassable terrain, something that will be implemented later on).

Dan's comments about making some changes to `Tile` makes a lot of sense to me. I used comments to document certain assumptions that were being made by the code -- definitely something to look into and I have some thoughts on how I want to move further with that.

---

Hopefully this is making some sense. And thank you for your interest! There's a lot of code here and the GUI code is almost necessarily convoluted so I apologize for that (GUI development in C++ is painful, nothing like it is in C#). Dan has helped me make some stride in improving the behind the scenes code. There's plenty of work to be done but progress is there.

And by all means, ask away! Sometimes by asking questions we can figure out better ways to do things.
