### ISSUE TITLE
Disallow bulldozing of SEED Lander

### ISSUE THREAD

**Issue by ldicker83** [OutpostUniverse/OPHD#1372]

**Comment by DanRStevens** [comment]
Although this would be a minor inconvenience for a few turns before the Command Center is operational, I don't think we actually need to disallow it. We should allow players to make stupid mistakes, and perhaps learn from them. Part of the fun of a game is in being allowed to fail, and to challenge the test the rules.

Besides, you do need to eventually bulldoze it, so any check would need to take that into account.

If anything, maybe we should give some feedback as to why it was a bad idea to bulldoze it when they did, otherwise I vote to close without any further changes.

**Comment by ldicker83** [comment]
I'm game to close this.
