### ISSUE TITLE
Debug-only crash during font loading after splash screen

### ISSUE THREAD

**Issue by cugone** [OutpostUniverse/OPHD#148]
While running from source in Debug mode the font loader crashes on Line 418 immediately after the splash screen ends (or is skipped) when trying to create the window title font: https://github.com/ldicker83/OPHD/blob/7be7a7aee576e03081b0fd5aade80b1faf97360c/src/UI/Core/Window.cpp#L36

No details are given for the crash other than "breakpoint triggered". The pointer to `srf` is non-nullptr, but the `blit` call immediately before the `free` call is suspect. Maybe the surface is still in use and this is a "free while in use" problem?

Crash Location: https://github.com/lairworks/nas2d-core/blob/4c75f05dd242852da0cb49f9cf6fbbb894155c61/src/Resources/Font.cpp#L418

**Comment by cugone** [comment]
There is a temporary workaround for this issue, in Visual Studio at least. Temporarily change the optimization options of `Release` to `Disabled` and you will be able to step through the program without being lied to. Just be sure to not push the change to the project file.

**Comment by ldicker83** [comment]
This was due to NAS2D using vcpkg for its dependencies but OPHD using NuGet. Basically, different parts of the code linking to different compiler/linker options. Switching OPHD over to using vcpkg fixes this issue though it introduces other issues (different change set.

Going to mark this closed as this has been resolved in the master branch.
