### ISSUE TITLE
Cleanup `extern SDL_Window* underlyingWindow;`

### ISSUE THREAD

**Issue by DanRStevens** [OutpostUniverse/OPHD#521]
There are a number of places with a comment about a hack, and then the following line of code:
```cpp
extern SDL_Window* underlyingWindow;
```

We should clean these up, and find a standard way of accomplishing what these lines are used for.

For OPHD, these uses are tied to the popup error dialog boxes.

Related references:
[SDL_GetWindowWMInfo](https://wiki.libsdl.org/SDL_GetWindowWMInfo)
[MessageBoxA](https://docs.microsoft.com/en-us/windows/win32/api/winuser/nf-winuser-messageboxa)

----

As part of this, we should clean up the include that occurs very late in `Common.cpp` (line 205):
```cpp
#if defined(WINDOWS) || defined(WIN32)
#include <SDL2/SDL_syswm.h>
```

**Comment by ldicker83** [comment]
It's truly a hack. My biggest concern was exposing implementation details (which this does). We could hide it behind a `void*` and require a cast when it's used. I think it may also be used in the EventHandler for grabbing/warping the mouse? But I don't completely remember.

Anyway, it's bad and I know it (hence the comment).

As for the comment, I wanted to keep that close to where it's used though it's used for pop up message boxes which I ultimately want to make an in-game thing instead of using the system message boxes as the system boxes don't play nice with fullscreen modes (and sorta breaks the look/feel).

**Comment by DanRStevens** [comment]
I would like to avoid casts where possible. Instead, we should perhaps look at adding functionality to NAS2D so we don't need access to this internal variable.

I checked the code more closely, and there are 3 instances of `extern SDL_Window`.
- Used by `HWND WIN32_getWindowHandle()`, which is further used to generate modal popup boxes
- Used by `bool windowMaximized()` to determine if the main window is maximized
- Used by `main` to maximize the main window (if the `maximized` option is set)

There didn't seem to be a concept of a main window exported by NAS2D that was used anywhere. That might be one area to start with. I assume it would be represented by a `Window` object. Assuming yes, we can add methods to query and set the maximized state.

The modal popups might be a bit harder to deal with. I suspect the real solution would be to use in game dismissable (non-modal) messages. We would likely need to update GUI objects to support such messages. The messages would then be presented through normal UI objects, and so we shouldn't have need of the Windows `HWND` handle.

I think I might de-prioritize the dismissable messages until other UI work can be completed. We should probably focus on updates to the event handling, and layout manager first.

**Comment by DanRStevens** [comment]
Adding reference to related upstream issue:
https://github.com/lairworks/nas2d-core/issues/701

**Comment by ldicker83** [comment]
I ultimately want to get rid of the modal dialog boxes which would make a Window object a concept that isn't really used in NAS2D. It's a case of 'using undocumented functions and/or features' using internal knowledge of how NAS2D handles things internally. It's prone to break should the underlying implementation change.

In OPHD's use of modal message boxes will be dropped in favor of non-native implementations (e.g., message boxes handled by OPHD's internal UI code). Those are there specifically to handle getting rid of the voice prompts that weren't useful in a quick way to get a release out the door. This is also the reason fullscreen mode was disabled in OPHD, something I want to reintroduce.

`bool windowMaximized();` is only ever used in the `WindowEventWrapper` class, specifically in `void onWindowResized(int w, int h)`. The check where it's used can probably be removed. If a window is maximized, we can store whatever values are in there, it doesn't actually matter because the window gets resized.

---

So the function `bool windowMaximized();` can be safely removed. The `WindowEventWrapper` is there as a kludge -- the NAS2D Delegate class is no longer to bind to stand-alone functions. Don't know why -- this wasn't an issue before it was modified. I'm sure there's a way to do this without using a class as a wrapper but that's what it's there for.

**Comment by DanRStevens** [comment]
I would be happy to see more integrated non-modal popup messages.

With that said, I think we could still make use of a `Window` class. At the very least, it would help improve the API. Currently the `Renderer` mixes quite a lot of different functionality together into one class. The `Renderer` has been pared down quite a bit, but it's still quite large. I think more of it should be separated out.

In particular, I think a `Window` class would make a better home for:
- setting a window title
- setting a window icon
- setting/unsetting maximized
- setting resizeability
- setting minimum window size
- setting window size
- resize event notifications
- input notifications (mouse, keyboard, touch, etc.)

The `Renderer` might represent a viewport within a window, which might very well take up the entire client area of the window. It would contain all the "draw" methods.

A few methods are a bit harder to class. Querying the desktop resolution seems more closely related to the `Window` than the `Renderer`, though it's not really a perfect fit since the desktop contains the `Window`, not the other way around. Perhaps it can be modeled as a desktop window, or perhaps it might evolve into yet another class.

----

None of this should be confused with the current "`Window`" class, which is perhaps more like a `Container` within a window. The actual OS window, along with a drawing viewport is currently combined into the `Renderer` object.

**Comment by ldicker83** [comment]
Okay, I think I'm board here. Makes sense to me.
