### ISSUE TITLE
Remove width() and height() methods

### ISSUE THREAD

**Issue by DanRStevens** [OutpostUniverse/OPHD#536]
A number of objects provide 3 very closely related methods:
- `size()`
- `width()`
- `height()`

To reduce code bulk, we can potentially eliminate the `width()` and `height()` methods, and instead replace them with uses of `size()`:
- `width()` => `size().x`
- `height()` => `size().y`

This would apply to the following classes:
- `Renderer` and derived
- `Image`
- `Sprite`
- `Font`
- `TileMap`
- `Control` and derived

One possible downside is that it may be slightly less efficient to fetch both values if only one is needed. On the other hand, a quick scan of the source code shows single values aren't used very frequently, and none of the single uses appear to be in performance critical code.

A few of those single use instances can probably be refactored away, since they are still used in pairs, just split over multiple lines/statements.

**Comment by ldicker83** [comment]
This seems like a good way to make the code more consistent across all interfaces. Width/Height are mostly just convenience functions anyway and since we're generally moving away from unpacked parameters this makes sense.

I suspect the performance overhead is negligible if not optimized away by the compiler. If profiling determines that there's a bottleneck somewhere we can figure out a way to handle it at that time.

**Comment by DanRStevens** [comment]
Realized a bit later on that `Font` works a bit differently. The `Font::size` method takes a string parameter, which is used to find the `width`. That means there's a much bigger difference between calling `Font::height` versus `Font::size("").y`. As such, `Font` may be left untouched by these changes.

Also untouched will be the setter methods. The `Control` set methods modify the control size, and trigger resize events. In a few places they are used to force minimum `Control` sizes. It may be awkward to replace that logic without support for clipping or clamping `NAS2D::Vector` by individual components.
