### ISSUE TITLE
Update Savegame load code to read StructureID

### ISSUE THREAD

**Issue by ldicker83** [OutpostUniverse/OPHD#618]
From #597 

Savegame load code will need to be modified to expect an ID value instead of a string literal. This is dependent on #598.

**Comment by DanRStevens** [comment]
Since saving an loading are tied together, maybe they should be handled as a single issue. Otherwise you get broken saved games if only one of them is addressed.

----

Internally, I think the game should prefer numeric IDs over string IDs. For saving/loading, I'd be fine with translating to/from string IDs. The string IDs would be somewhat nicer if manually editing a text file.

----

I'm kind of thinking the structure name could become the tag name:
```
<agridome propert1="value1" ... />
```

Not sure what the current format is though.

**Comment by ldicker83** [comment]
The structure strings have potential spaces in them. They're literally the decoration names. I know that it would be easier to read if manually editing a savegame but the intention isn't to make manual savegame editing easy, it's to make it so I don't have to do so much jumping through hoops in the code.

Additionally, I'd like to eventually replace the XML with an actual binary savegame. The choice for XML was just for the beginning of development so I could play with the internal values. Visual Studio's debugger has gotten a lot better (and I've gotten a lot better with it) so I think it's better to do it this way.

I could put these two tasks into a single PR, shouldn't be an issue, but I did want to break each task since saving/loading are very different operations when it comes to TinyXML. Loading code is far more verbose than saving. :/
