### ISSUE TITLE
Add Structure String Table

### ISSUE THREAD

**Issue by ldicker83** [OutpostUniverse/OPHD#619]
From #597:

> A string table will need to be defined with a numeric identifier as a key (e.g., StructureID enum). Traditionally I've done this as a std::map but I think a std::array will do the trick here especially if the table lookup is done through a function that returns a std::string and requires a class enum.

**Comment by DanRStevens** [comment]
I agree, and have some thoughts to add.

----

I've noticed there is often a need to convert between numeric IDs and string IDs. Most code in the project falls in two camps:
- `std::map`:
  - `enum class` => `std::string` (without `static_cast`)
- `std::array`:
  - `enum class` => `std::size_t` (using `static_cast`, though optional depending on context)
  - `std::size_t` => `std::string`

When converting the reverse direction, from `std::string` to either a `std::size_t` numeric ID, or to an `enum class` ID, a `std::map` is probably the simplest way.

----

I think the `std::array` approach above becomes nicer if hardcoded values are avoided, and so you avoid the need to manually specify enum value names. Take for instance the `DirectionOffset` code, which allows for iterating over all directions, without necessarily naming each direction:
```cpp
for (const auto direction : DirectionScan3x3)
{
  // ...
}
```

Of course, I think more can be done with the direction code, as specific direction names are still common.

In terms of the `Structure` code, things may be a bit harder due to many unique properties, though is perhaps possible with some refactoring. For instance, when building a structure, the icon selected might map to a `std::size_t` index, which could be passed to the code to place a new structure. There may be no need to specifically name the structure type.

When converting from IDs to specific subclass instances, you'll probably need a `switch` statement. At least you need a `switch` with the current architecture using a set of subclasses. Maybe there's another more data driven way to handle this.

Assuming the class hierarchy is maintained, when doing display, we can use `virtual` function dispatch to avoid having to test for a specific structure ID to determine what to do. Actually, I've noticed in general, you can often replace big ugly `switch` blocks by using `virtual` function dispatch instead. Internally, the implementation mechanics is pretty similar, though in terms of code maintainability, I find `virtual` functions are cleaner.

----

Ideally, I'd like to minimize the use of enum value names. They tend to be associated with large `switch` blocks (or equivalent cascaded `if` blocks), which I find are a bit of a code smell. Such `switch` blocks often end up being repeated, resulting in duplication of code structure, and requiring a lot of maintenance when new enum value names are added. They can often be replaced by array lookup, or `virtual` function dispatch, which is generally better for maintenance and readability.
