### ISSUE TITLE
StructureInspector improvements

### ISSUE THREAD

**Issue by Brett208** [OutpostUniverse/OPHD#621]
I've been trying to improve the look of the StructureInspector. Below is a picture of the smelter. I'll try to push the changeset this weekend unless people are opposed to the new look. It has been a lot of work for not a lot of visual gain.

<img width="261" alt="StructureInspector" src="https://user-images.githubusercontent.com/15183337/90209141-8ac35700-ddb8-11ea-9012-b8251156b171.png">

**Comment by DanRStevens** [comment]
Hey, that looks nice.

----

As for a lot of work, yes the graphics code is currently very time intensive to develop. I think we need to do more to make GUI building easier. I see the difficulty of producing new UIs as one of the major impediments to development.

I think one of the difficulties that makes it a slow and laborious task, is having to manually specify so much of the positioning. That's made worse by having to compile and run the game to test the results, though I don't think a visual designer to see the results is necessarily the way to go, but rather we should seek to eliminate much of the manual positioning.

The event handling seems to be another area to look at. Having to manually connect to event sources, and disconnect on destruction seems like more work than I'd like. Plus, if you get it wrong and don't disconnect from a `Signal` before an object is destructed, you can get crash bugs. I think I'd like to use `virtual` function dispatch for delivering events to subclasses, and reserve `Signal` use to delivering events to containers or unrelated objects.

These ideas have been brewing in the back of my mind. I think at some point we need to formalize them in an issue. And I'm glad you're working on some of the UI code, since having that experience will help us formalize where we want to go with it.
