### ISSUE TITLE
Add typecast method to StructureManager to get lists of derived structure types

### ISSUE THREAD

**Issue by ldicker83** [OutpostUniverse/OPHD#714]
From PR #713, @DanRStevens mentioned a way to improved some of the code by adding a templated method to StructureManager that allows getting derived structure types:

> This gets me thinking, maybe we could have a templated `StructureManager` method that allows getting structures of a certain type, and would use that exact type for the return value. Then you could write something like:
> ```cpp
> const auto warehouses = structureManager.structureList<Warehouse>();
> for (auto warehouse : warehouses)
> {
>   warehouse->warehouseSpecificMethod();
> }
> ```
> 
> _Originally posted by @DanRStevens in https://github.com/OutpostUniverse/OPHD/pull/713#discussion_r495585281_

This sound like a great way to improve code use

**Comment by DanRStevens** [comment]
I came across an article that relates to this:
https://gpfault.net/posts/mapping-types-to-values.txt.html

I don't know that we necessarily want to implement as described in the article, though it does contain an explanation of how to produce a type to value map. As types are compile time entities, there is no way to use a `std::map`, as those require runtime values for the keys, and we want a type as the lookup key. Instead, a template can be used, where template specialization is used to set output values for each input type key.

```cpp
template <typename T>
struct StructTypeToEnumValue { static const StructureClass enumValue; };

template <>
const StructureClass StructTypeToEnumValue<CommandCenter>::enumValue = StructureClass::Command;

// Repeat for remaining classes ...
```

Of course this is rather tedious to maintain. Each time a class is added, it would require updating the `StructTypeToEnumValue` mapping.

The article discusses one way to ease that burden. There may be others.

**Comment by ldicker83** [comment]
I forgot we opened this issue.

But holy hell yes I really want to take advantage of this. The more I go iterating over lists of structures I frequently find myself casting to derived types. On the one hand that's fine because I already know the derived type by context but still, having to create temporary variables out of type casts from a base class gets overly verbose.

**Comment by DanRStevens** [comment]
Yeah, I was looking over the code the other night and thinking there must be a way to simplify creating new classes. Wasn't sure I had a particularly good suggestion at the time.

Each `Structure` class has an associated enum type, and requires the enum value be set by the base class constructor from the derived class constructor. Actually, there's no guarantee the value passed to the base class constructor will even match the derived class.

I contemplated replacing the base class field with a virtual method that returns the enum value for that class type, without needing to store the value. I'd also considered adding a static method to the derived classes to return the enum value, allowing the two to be associated with each other without needing an instance of the class. Though this all feels like it was just pushing the problem around, not really solving it any better.

I had also thought it might be wise to reduce reliance on the enum values. Is the enum even needed? Perhaps virtual methods could be used to make decisions that would normally have relied on the enum value.

**Comment by ldicker83** [comment]
I suppose it could be dropped? The enum is used to group different types of structures together versus the ID which is the specific ID of a structure (e.g., Residence Mk1, Mk2 and Mk3 are all Residence class structures but they all have a different ID since they can all be built individually).

Not sure how to get around that since they're grouped together by class to be updated in sequence.

**Comment by rmtoth** [comment]
The core design issue seems to be that StructureClass is not tied to an actual C++ class. Even if you iterate over all structures of a given SC, you still can't access members related to that SC.
The simplest solution would be to add classes for SCs and have the individual structure types inherit from their SC class rather than directly from Structure.
If you want to open the possibility of having structures doing multiple things, then you may want to consider multiple inheritance or something similar.

**Comment by ldicker83** [comment]
Honestly, fair point. I'd thought about derived types -- a lot of this is from the initial design where I only intended everything to derive directly from Structure. In hindsight this was a naïve approach.

That stated, the name StructureClass is a bit of misnomer -- it comes from the original game's classification of structures which used the same terminology, Structure Class.

Anyway, I think your proposal makes sense. There's some general trend toward that with food producers and power generation structures. It wouldn't be difficult to do the same with the rest of the structures thought it would be a generally large change set.

After that this could be done with a basic templatized `std::vector` list of actual structure classes.

**Comment by DanRStevens** [comment]
I would like to avoid multiple inheritance if at all possible.

May be a valid point about solving the wrong issue here. I don't think there's a super clear idea on what we want the structure code to look like.

I think because there are overlapping concerns, such as food storage and power production for things like Command Centers, I'm somewhat tempted to suggest a more flat hierarchy, where each structure could potentially do many things, based on attributes, which apply equally to all structures. That would give lots of flexibility in terms of combining different abilities into new structures, which may have benefits for modding. Though I'm uncertain right now how that would work in practice, and if it might end up seeming kind of messy. Mind you, the current state feels kind of messy for other reasons, such as having to update so many different parts of the code to implement new structure abilities, or new structures.

**Comment by rmtoth** [comment]
Combinatorial flexibility without multiple inheritance sounds like an entity component system. I refrained from suggesting an ECS since it seemed like overkill for something like OPHD, but on the other hand I think it can be made quite lightweight. I can draft an ECS system for Structures if you think that's the way you want to go.

**Comment by DanRStevens** [comment]
Might be nice to toss around a few short ideas, and see if it has traction. I would be interested to hear what you have to say.

**Comment by DanRStevens** [comment]
For anyone else who was unfamiliar with the term **Entity Component System** (**ECS**), here are a couple of links:
- https://en.wikipedia.org/wiki/Entity_component_system
- https://medium.com/ingeniouslysimple/entities-components-and-systems-89c31464240d

**Comment by ldicker83** [comment]
I'm game for something light weight that could solve this problem and make developing structures going forward simpler. It could also be expanded upon in later projects so no objections here!

**Comment by rmtoth** [comment]
I did a very rough draft of a minimalistic ECS in my fork: https://github.com/rmtoth/OPHD/tree/ecs
I only converted the RobotCommand structure to place its logic in a component and left the rest as is for now.
The amount of code doesn't really change all that much, so I don't know if you feel this will achieve the code cleanup you wanted.
Composability shouldn't be a problem. I don't have a good grasp on how significant that is going to be.

There's one big issue that deserves some thought before I'd be comfortable recommending this kind of system: how to achieve the meticulously specified priority order in StructureManager::update.

**Comment by rmtoth** [comment]
Updated the ECS branch. It can now be run and seems to work. I'll see if I can move more functionality from StructureClass to StructureComponent. It should be a fairly mechanical process for the most part.

**Comment by DanRStevens** [comment]
Hmm, interesting. That's a somewhat different solution than I'd considered before.

Sounds like perhaps we should have a deeper discussion on this. Maybe we should create a new issue for this idea, and link back to this one. We're maybe starting to get a little further and deeper into related topics, beyond the initial scope of being able to iterate over a certain type of structure, without needing casts in client code.

We'll probably need to detail impacts on saving/loading code. In particular, pointers require translation when saving/loading, whereas index and ID values do not. If we could use a data format that serialized easily, that might help.

Reading the code was interesting, though we'll probably want to summarize the idea in high level text. Right now my understand still feels a bit vague, and so it's not obvious to reason about the details on how this might impact the code.

I assume `UID` meant unique ID? I'd prefer using enum values over something like FOURCC. I think at some level we will need some kind of enum or index value to represent the type of a structure. Though where it gets used could potentially be minimized.

**Comment by rmtoth** [comment]
>Maybe we should create a new issue for this idea, and link back to this one
Sure, I didn't mean to sidetrack the bug. I'm still feeling around for how you communicate general ideas as I'm not used to contributing on github.

I think the XML format you're using is actually very well suited to serialize the ECS, with one element for the structure and one child element within it per component. I don't know if there are cross-structure references in the XML, but I think those can also remain largely untouched. A structure can only have one component of a given type, so if you need to reference some other structure's component, you can just reference the structure itself.

> I assume UID meant unique ID?
Yeah. I don't have much of an opinion on how to do it.

> I think at some level we will need some kind of enum or index value to represent the type of a structure.
Do you mean in addition to the StructureID?

**Comment by DanRStevens** [comment]
I was looking at an old abandoned branch that seemed to relate to this issue. It wasn't so much about getting a list of derived structures, but to create new structures based on a structure type. The idea was flawed and didn't work, though I wanted to leave a note as to why.

The code was structured something like this:
```cpp
template <typename... Params>
Structure* newStructure(StructureID type, Params&&... params)
{
	switch (type)
	{
		case StructureID::SID_AGRIDOME:
			return new Agridome(std::forward<Params>(params)...);
		case StructureID::SID_AIR_SHAFT:
			return new AirShaft(std::forward<Params>(params)...);
		// ...
```

The problem with that code is the `type` is a runtime parameter, while the parameter list is a compile time parameter, and all code in the function must be valid for the given type list. The problem was, some structure classes had a default constructor, while others didn't, so when an empty parameter list was passed the code would fail to compile because some structure classes didn't have a default constructor that was callable. It didn't matter if the `type` parameter in those cases was for a different structure that did have a default constructor, since the code needed to be compiled first (and be valid, for every `case`), and only at runtime would the `type` value be considered.

To work around that, the `type` parameter could be moved to compile time, which would allow the compiler to compile out the irrelevant `switch` cases, and avoid a compile error. That looked something like:
```cpp
template <StructureID type, typename... Params>
Structure* newStructure(Params&&... params)
{
    // ...
```

The problem with this code, is that now `type` needed to be known at compile time, and so it was not possible to call the function with a runtime value. The original function had been used something like:
```cpp
Structure* StructureCatalogue::get(StructureID type)
{
	Structure* structure = nullptr;

	switch (type)
	{
		case StructureID::SID_AGRIDOME:
		case StructureID::SID_AIR_SHAFT:
		// ...
		case StructureID::SID_UNIVERSITY:
		case StructureID::SID_WAREHOUSE:
			structure = newStructure(type);
			break;
```

The call would have needed to change to:
```cpp
			structure = newStructure<type>();
```

However, that wasn't possible because `type` was a dynamic parameter to that function too.

Basically, there wasn't really anyway to get around a large runtime `switch` statement if you needed to translate from runtime values to compile time types.

----

Example error from the first attempt:

> OPHD/StructureCatalogue.cpp: In instantiation of ‘Structure* {anonymous}::newStructure(StructureID, Params&& ...) [with Params = {}]’:
> OPHD/StructureCatalogue.cpp:271:28:   required from here
> OPHD/StructureCatalogue.cpp:143:40: error: use of deleted function ‘CargoLander::CargoLander()’
>   143 |                                 return new CargoLander(std::forward<Params>(params)...);
>       |                                        ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
> In file included from OPHD/Things/Structures/Structures.h:6,
>                  from OPHD/StructureCatalogue.cpp:4:
> OPHD/Things/Structures/CargoLander.h:44:9: note: declared here
>    44 |         CargoLander() = delete;
>       |         ^~~~~~~~~~~

----

Example error from the second attempt:

> OPHD/StructureCatalogue.cpp: In static member function ‘static Structure* StructureCatalogue::get(StructureID)’:
> OPHD/StructureCatalogue.cpp:271:55: error: no matching function for call to ‘newStructure<type>()’
>   271 |                         structure = newStructure<type>();
>       |                                     ~~~~~~~~~~~~~~~~~~^~
> OPHD/StructureCatalogue.cpp:134:20: note: candidate: ‘template<StructureID type, class ... Params> Structure* {anonymous}::newStructure(Params&& ...)’
>   134 |         Structure* newStructure(Params&&... params)
>       |                    ^~~~~~~~~~~~
> OPHD/StructureCatalogue.cpp:134:20: note:   template argument deduction/substitution failed:
> OPHD/StructureCatalogue.cpp:271:55: error: ‘type’ is not a constant expression
>   271 |                         structure = newStructure<type>();
>       |                                     ~~~~~~~~~~~~~~~~~~^~
> OPHD/StructureCatalogue.cpp:271:55: note: in template argument for type ‘StructureID’

----

I think the idea to use an Entity Component System (#824) sounds more and more attractive. In particular, it would be nice to be able to create and use various structure types without resorting to large `switch` statements, and their associated maintenance.

It would be particularly neat if structures could be defined in an external data file, and expressed as some kind of structure meta data. You could potentially create a new structure by using an index into the meta data, rather than large `switch` blocks to translate an enum value to a compile time class type.
