### ISSUE TITLE
Right clicking on disabled robot command center causes game to crash

### ISSUE THREAD

**Issue by Brett208** [OutpostUniverse/OPHD#742]
**Version:** 0.8.0
**OS:** Windows 10 64 Bit
**Description:** When right clicking on the Robot Command Center, I received the Application Error Invalid map<K, T> key. After clicking OK, the game closed out (assumed I crashed it somehow).

<img width="439" alt="InvalidMapKeyRobotCommandCenter" src="https://user-images.githubusercontent.com/15183337/103449948-54aa4500-4c7d-11eb-9aba-10c5df71d232.png">

**Comment by ldicker83** [comment]
Welp, not the GUI event hook issue I thought it would be. I know exactly what this is -- with the switch to using `std::map::at()` instead of `std::map::operator[]`, missing key/value pairs aren't automatically added so it breaks. Means I need to look at that and explicitly create the key/value pair. Had to fix a lot of issues with this.

Gonna have to look at all places that `std::map::at()` and really check those out to stomp these out.

Thanks for the report!

**Comment by ldicker83** [comment]
This issue was fixed in PR #751
