### ISSUE TITLE
Selection guides are not drawing properly

### ISSUE THREAD

**Issue by Brett208** [OutpostUniverse/OPHD#745]
**Version:** 0.8.0
**OS:** Windows 10 64 Bit
**Description:** In several areas where squares are drawn to show selections, a line is drawn through the icon diagonally instead of completing the box.

<img width="122" alt="Selection Box OPHD" src="https://user-images.githubusercontent.com/15183337/103450114-84f2e300-4c7f-11eb-8022-9793f5fd6f9d.png">

**Comment by ldicker83** [comment]
This looks like a problem with the NAS2D middleware `Renderer::drawBox()` function. I didn't think that had been changed, will have to look into it and get it corrected for the next version. All of the `drawBox` calls seem to have the same problem. It's visible on the mini map, the full-screen UI's and the FileIO windows.

Interestingly enough this issue isn't present in the debug build. Have a sneaking suspicion about where to look for this. Blah, how annoying -_-

**Comment by ldicker83** [comment]
So this appears to have been resolved? I'm not sure if it was a compiler bug that lead to weirdness but building in release mode in the current version of Visual Studio 2019 with the latest pull from NAS2D (unmodified code) no longer shows this issue. I'll mark it as resolved for now since I can't replicate it anymore.

**Comment by DanRStevens** [comment]
Is it possible an OpenGL state was being set in some prototype code that may have inadvertently affected the line drawing code? Or maybe a change to the `Rectangle` code that calculates corner points? Anyway, probably best to close unless it can be reproduced.

**Comment by ldicker83** [comment]
I'm not sure. What I discovered is that the code, unaltered, worked as expected in Debug but then broke in Release. By m removing the pre-calculated corners, specifically these lines in `RendererOpenGL::drawBox()`:

```cpp
	const auto adjustedCrossYPoint = rect.crossYPoint() + Vector{0.0f, 0.5f};
	const auto adjustedEndPoint = rect.endPoint() + Vector{0.0f, 0.5f};
```

I didn't get too deep into what was going on though I did notice in release if I tried to get the value of either of those variables they weren't available. Anyway, for the 0.8.0a build I just moved the expression into the `drawLine()` calls to get a quick fix.

Since then there have been three updates to Visual Studio and the problem vanished. There were a couple of updates to NAS2D's code but none in the Renderer as I recall, they were string functions I believe.

Anyway, since that build I have it in release with the unmodified NAS2D code and it works as expected so... I dunno? I can only guess some sort of compiler optimization may have gotten in the way, I know Microsoft has patched a number of things in the compiler so... yeah I dunno.

Serves as a good example of why I should actually run programs built in Release mode before actually bundling them and releasing. Assuming it works in Release because it works in Debug is a mistake that's bitten the ass of many weary developers.
