### ISSUE TITLE
Refactor inCommRange(NAS2D::Point<int>)

### ISSUE THREAD

**Issue by ldicker83** [OutpostUniverse/OPHD#806]
I noticed that `bool inCommRange(NAS2D::Point<int> position)` located in MapViewStateHelper.cpp reimplements basic distance functions when we should instead be using the `Tile::distanceTo(Tile*)` function. Will make the function a lot easier to read and reduce code redundancy.

**Comment by DanRStevens** [comment]
I think you might want to go the other direction on this. A `Tile` has a `position` (`Point`), though a `Point` may not be associated with a `Tile`. Effectively the `Point` type is more abstract, and is the real thing you want to calculate distances between, or check for a distance threshold.

I think it would be better to implement distance calculations in terms of `Point` and `Vector`, which now have methods to help with that. In particular, there is now a `Vector::lengthSquared()` method to help with this.

A `Vector::length` was omitted for two main reasons:
1) `Vector` is a templated struct, so choosing the return type of `length` was non-obvious. Maybe you want it to be `int`, maybe you want it to be `double`.
2) Decisions made based on `length` or distance thresholds can be more efficiently handled using length squared, which also sidesteps the return type problem.

Example:
```cpp
const auto maxCCRangeSquared = constants::ROBOT_COM_RANGE * constants::ROBOT_COM_RANGE;
const auto ccDistance = position - ccLocation();
if (ccDistance.lengthSquared() <= maxCCRangeSquared)
{
	return true;
}
```

----

I suspect what we want is a general purpose function that can check if two `Point` objects are within some threshold `distance`:
```cpp
if (isWithinDistance(position, ccLocation, maxCCRange))
```

Of course, if you write it that way, you end up needing to square the range for every check, rather than doing it once upfront.

I suppose there are other ways to handle it though, such as methods that take a range of points and determine if any are within some distance. Such a method could do the squaring once internally, and then check every pair of points using the length squared.

**Comment by ldicker83** [comment]
I'm open to suggestion here. Ultimately I just want to see it done in a really simple to use way. It's why I like the Tile::distanceTo(Tile) function. It's really easy to understand how to use it.

**Comment by belgianguy** [comment]
I suppose the "is in range of" will be applicable to multiple scenarios, not just placing robots. E.g.: Police structure influence on the transformation of Residential into Red Light Districts? Area of effect damage when a Hot Lab or Tokamak explodes, disaster impact area, ...?

I toyed with the distanceTo function on my fork, but if this functionality is desired in mutiple scenarios outside of communication range when placing robots, I can see value in it being generalized.

Could such "range is important to the concept" be translated into a trait of some sort? E.g. a CommunicationsManager that has the ability to check communication range (for Command Centers and Communication Towers), a CrimeManager that has the ability to tell the crime for a certain tile depending on Police structures (if any) surrounding it? 

Conceptually this can be seen as different "layers", eg a "communications layer" , "disaster layer", "crime layer", which translate to combinations of circles in a rectangular plane.

Reference to my fork: https://github.com/belgianguy/OPHD/commit/57ce194e2912b5f4dafead949ebb7259cc00b031

**Comment by DanRStevens** [comment]
There are two related problems here:
1) `point1.distanceTo(point2)` -> `float`
2) `isInRange(point1, point2, distance)` -> `bool`

You can use 1 to implement 2 in an obvious way, but it's actually more efficient to implement 2 than to implement 1. What we need here is a solution for problem 2.

The main reason that problem 1 has less efficient solutions, is because it requires use of a square root, which is a relatively expensive operation. The square root algorithm requires iteration to converge on a solution, and may have a fair bit of calculation during each iteration. Further, if you're returning the value as `float`, there are type conversion costs as well. Translating between `int` and `float` is surprisingly expensive compared to other simple numeric operations. Most square root algorithms require floating point for the convergence to work, so you're paying to convert to `float` before starting the operation, and then paying to convert back when doing the distance comparison.

When implementing a solution to problem 2, you can rely on comparing squares instead of comparing square roots:
For `a > 0` and `b > 0`:
`a <= b` <=> if `a * a <= b * b`
So instead of solving 1:
`sqrt((x2 - x1) * (x2 - x1) + (y2 - y1) * (y2 - y1)) <= distance`
You can instead solve 2:
`(x2 - x1) * (x2 - x1) + (y2 - y1) * (y2 - y1) <= distance * distance`
With solution 2 there is no need for `sqrt`, and no need for conversion to and from `float`. Solution 2 is probably about an order of magnitude faster than solution 1.

I know this isn't a huge issue for a turn based game, but if you can be more efficient about something, then why not? Especially if it leads to more clarity about what exact problem is being solved.

I should also point out that often you have a collection of points that will be compared to a single point. That means the efficiency of the distance check is multiplied by how many points need to be checked. Not only is solution 2 an order of magnitude faster, but for a list of points to compare, you can factor out the `distance * distance` part, since it is constant for all comparisons, so you have even less calculation in the loop.

**Comment by ldicker83** [comment]
Solution 2 is also very viable. While I'm a lot less worried about efficiency here since these aren't functions that are being run frequently, it would be irresponsible (I think) to just ignore it.

That stated, a function like `isInRange(point, point, distance)` is entirely acceptable to me. But I think it means that we should be consistent in its use everywhere. Which would mean removing the `distanceTo()` function. I see a pull request that I think addresses this so I'll be looking over that here in a bit.

**Comment by DanRStevens** [comment]
I think we should still have a distance function. Just that often we don't need to calculate the actual distance if all we want to know is if something is within a certain distance.

The ore calculation based on route length is something that is dependent on the actual distance value. Though that may be calculated in an entirely different way, so perhaps not applicable to this discussion. Just pointing out that some calculation do need the actual distance, while others can rely on an in range check that doesn't need to calculate the actual distance.
