### ISSUE TITLE
Update Slider design

### ISSUE THREAD

**Issue by DanRStevens** [OutpostUniverse/OPHD#893]
There are a number of design aspects of the `Slider` class that get discussed from time to time. Perhaps it's time to make some adjustments.

I often feel the use of `float` for the scroll bar value is a bit odd. Float is essentially equivalent to scientific notation, with a wide dynamic range, but limited precision. The spacing between adjacent float values is not uniform, particularly over a wide range. The graphical display of a scroll bar doesn't represent the dynamic range of float values. Rather there is generally a fixed smallest increment. That would make integers a much more appropriate unit for scroll bars. Even when non-integer values are needed, the fixed precision is often maintained, and so simply scaling an integer value may be most appropriate. I propose updating the scroll bar to use integer based position values. Alternatively, I would be willing to consider using a template to specify the underlying type.

We should drop support for normalization. That is an external concern. If calling code needs normalization, they can do it themselves. Similarly, we should drop support for "backward mode". This can be handled externally as part of normalization.

We should rename `thumbPosition` to `value`. Similarly `length` should probably be named `max`.

Users should be able to click and drag the thumb. Currently that is not support, and clicking the thumb seems roughly equivalent to clicking an empty area of the scroll bar.

It might make sense to support configurable small and large increment values. Clicking one of the up/down buttons would be the small increment, or up/down arrow keys. Clicking the empty area of the scroll bar, or using page up/down would be a large increment. Draging the thumb would be jump to behaviour, using proportional positioning, accurate to the pixel.

We should add some support for keyboard navigation and operation.

I have mixed feeling about support for displaying the value over top of the scroll bar. Is that something we should support in the control, or should that be moved to an external concern?

Should we use an `enum` for vertical versus horizontal, or should that become part of the class type, and so we'd have two different scroll bar classes?

Btw, how common is the term "Slider"? I'm perhaps more used to the term "ScrollBar". Curious what other people think there. I had a bit of trouble finding the header file earlier today because I was looking for the wrong name.

**Comment by ldicker83** [comment]
ScrollBar is a more appropriate name for this Control. A [Slider](https://docs.microsoft.com/en-us/windows/win32/controls/trackbar-controls) is a different mechanism, probably not one I really see being used in OPHD since we have [Spin Controls](https://docs.microsoft.com/en-us/windows/win32/uxguide/ctrl-spin-controls) instead. Sliders may be useful later on for task delegation of AI's or scientists, population, research levels, whatever but we can approach that later.

Anyway, ScrollBar I think is a good option to use. I'm not sure having two discrete classes for vertical/horizontal movement is really necessary -- a simple enumerated type could be used for that behavior. Ultimately the only real difference is in how the bar is drawn and the axis along which the thumb is moved.

**Comment by Brett208** [comment]
My convention would also be to call this a ScrollBar as opposed to Slider.

**Comment by DanRStevens** [comment]
Ahh yes, I do associate "Slider" with that other control. Good point.

Let's rename it then.

**Comment by DanRStevens** [comment]
The major points of this issue are largely addressed. I'm going to close it. I moved one outstanding item to it's own issue, where it will have greater focus.
