### ISSUE TITLE
Truck routes don't update on Seed Smelter breakdown

### ISSUE THREAD

**Issue by agryson** [OutpostUniverse/OPHD#927]
When the seed smelter breaks down from old age, truck routes do not invalidate as they would be expected to. 
Despite the presence of another, functioning smelter to route to, no processing occurs and the old route remains visible and active until the structure is dozed.

[See discussion here](https://discord.com/channels/661360753512546324/843667987059834911/848877691033485332)

Save file illustrating the issue: [SmelterBug.zip](https://github.com/OutpostUniverse/OPHD/files/6571799/SmelterBug.zip)

**Comment by ldicker83** [comment]
Werps.

Thanks for the report! I think I know exactly what the issue is, will resolve this one shortly.

**Comment by ldicker83** [comment]
Reference for myself -- the issue lies here: https://github.com/OutpostUniverse/OPHD/blob/bccf78378b8cc9830cb3e5147a1b57070d5d95c6/OPHD/States/MapViewStateTurn.cpp#L36

Code iterates over all Smelters but doesn't check if it's in an operational state.

While on the subject, if a Smelter is Idle, it's not going to be processing anything so mines should skip an idle Smelter and attempt to route to a different Smelter. It will give up if there are no smelters that aren't in an operational state.

**Comment by agryson** [comment]
Thanks for looking into it.

This may already be handled but be careful of where unsmelted ore goes if no smelter is available, it shouldn't just disappear...

**Comment by ldicker83** [comment]
> Thanks for looking into it.
> 
> This may already be handled but be careful of where unsmelted ore goes if no smelter is available, it shouldn't just disappear...

Agreed -- Current logic should have it just stay at the Mine until its production lines fill up and so the mine goes Idle until the pools are emptied out enough to resume production.
