### ISSUE TITLE
Exception Thrown when digging an elevator shaft deeper

### ISSUE THREAD

**Issue by Brett208** [OutpostUniverse/OPHD#930]
Build: Current Master branch on 31May2021
Configuration: x64 Debug Build, running in debug mode in VS2019
OS: Windows 10 64 bit

When trying to make an elevator shaft deeper by digging on top of an existing shaft, an exception is thrown (IE trying to go from UG1 to UG2 on a Mars type planet).

<img width="884" alt="DiggingDownOnTopOfElevator" src="https://user-images.githubusercontent.com/15183337/120259997-f9e43c00-c262-11eb-926e-884a8eada51c.png">

<img width="936" alt="DiggingDownOnTopOfElevator VisualStudio View" src="https://user-images.githubusercontent.com/15183337/120259587-3e230c80-c262-11eb-893a-0fc1720cdd2a.png">

<img width="933" alt="DiggingDownOnTopOfElevator Disassembly View" src="https://user-images.githubusercontent.com/15183337/120259588-3e230c80-c262-11eb-96e9-bfa5d2e1d311.png">

I'm forgetting where to find the saved game, trying to rummage through the AppData folders and it is getting late. Should be easy to reproduce, but can dig it up later if needed.

**Comment by DanRStevens** [comment]
I updated that code recently. I consolidated the error checking at the end of the function. This might be due to items being deleted from the collection above. That may cause the `end()` marker of the collection to be updated, and so the comparison is no longer valid.

I think I have enough info to fix this.
